
    server:
      port: 2021

    spring:
      datasource:
        url: jdbc:postgresql://localhost:5432/snappfood
        username: postgres
        password: 106513545


      jpa:
        database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
        database: postgresql
        hibernate:
          ddl-auto: update
        show-sql: true


    minio:
      buket:
        name: snappfood
      default:
        folder: "/"
      access:
        name: minioadmin
        secret: minioadmin

      url:  http://127.0.0.1:9000